; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "RHI"
#ifndef PublishDir
  #define PublishDir SourcePath + "RenoDXCommander\bin\x64\Release\net8.0-windows10.0.19041.0\win-x64"
#endif
#ifndef InstallerOutputDir
  #define InstallerOutputDir SourcePath
#endif
#ifndef MyAppVersion
  #define MyAppVersion GetVersionNumbersString(PublishDir + "\RHI.exe")
#endif
#define MyAppPublisher "RankFTW"
#define MyAppURL "www.github.com/rankftw"
#define MyAppExeName "RHI.exe"

[Setup]
AppId={{05342962-55F5-4BA3-BFD3-DBA01D2B8BCB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
OutputDir={#InstallerOutputDir}
OutputBaseFilename=RHI-Setup
SetupIconFile={#PublishDir}\icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\RHI"

[Run]
; Download Windows App Runtime 2.5.1 if not already installed (only runs if missing)
Filename: "powershell.exe"; Parameters: "-NoProfile -NonInteractive -WindowStyle Hidden -Command ""Invoke-WebRequest -Uri 'https://aka.ms/windowsappsdk/2.5/latest/windowsappruntimeinstall-x64.exe' -OutFile '{tmp}\windowsappruntimeinstall-x64.exe' -UseBasicParsing"""; StatusMsg: "Downloading Windows App Runtime 2.5.1..."; Flags: waituntilterminated; Check: NeedsWindowsAppRuntime
; Install Windows App Runtime 2.5.1 if not already installed
Filename: "{tmp}\windowsappruntimeinstall-x64.exe"; Parameters: "--quiet"; StatusMsg: "Installing Windows App Runtime 2.5.1..."; Flags: waituntilterminated; Check: NeedsWindowsAppRuntime
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent; BeforeInstall: BeginForegroundHandoff; AfterInstall: CompleteForegroundHandoff

[Code]
const
  ForegroundReadyProperty = 'RHI.ForegroundReady.v1';
  ForegroundRequestMessage = 'RHI.ForegroundRequest.v1';

var
  ForegroundProgress: TOutputProgressWizardPage;

function FindNextTopLevelWindow(Parent, AfterWindow: HWND; ClassName, WindowName: Longint): HWND;
  external 'FindWindowExW@user32.dll stdcall';
function ReadWindowProperty(Window: HWND; Name: String): THandle;
  external 'GetPropW@user32.dll stdcall';
function ReadWindowProcessId(Window: HWND; var ProcessId: DWORD): DWORD;
  external 'GetWindowThreadProcessId@user32.dll stdcall';
function OpenTargetProcess(Access: DWORD; InheritHandle: BOOL; ProcessId: DWORD): THandle;
  external 'OpenProcess@kernel32.dll stdcall';
function ReadProcessImage(Process: THandle; Flags: DWORD; FileName: String; var Size: DWORD): BOOL;
  external 'QueryFullProcessImageNameW@kernel32.dll stdcall';
function CloseTargetHandle(Handle: THandle): BOOL;
  external 'CloseHandle@kernel32.dll stdcall';
function GrantForegroundPermission(ProcessId: DWORD): BOOL;
  external 'AllowSetForegroundWindow@user32.dll stdcall';
function RegisterForegroundMessage(Name: String): UINT;
  external 'RegisterWindowMessageW@user32.dll stdcall';
function PostForegroundMessage(Window: HWND; Message: UINT; WParam: LongWord; LParam: Longint): BOOL;
  external 'PostMessageW@user32.dll stdcall';

function IsInstalledRhiProcess(ProcessId: DWORD): Boolean;
var
  Process: THandle;
  ImagePath: String;
  Size: DWORD;
begin
  Result := False;
  Process := OpenTargetProcess($1000, False, ProcessId);
  if Process = 0 then Exit;
  try
    Size := 32768;
    SetLength(ImagePath, Size);
    if ReadProcessImage(Process, 0, ImagePath, Size) then
    begin
      SetLength(ImagePath, Size);
      Result := CompareText(ImagePath, ExpandConstant('{app}\{#MyAppExeName}')) = 0;
    end;
  finally
    CloseTargetHandle(Process);
  end;
end;

function FindReadyRhiWindow(var ProcessId: DWORD): HWND;
var
  Window: HWND;
begin
  Result := 0;
  Window := FindNextTopLevelWindow(0, 0, 0, 0);
  while Window <> 0 do
  begin
    if ReadWindowProperty(Window, ForegroundReadyProperty) = 1 then
    begin
      ProcessId := 0;
      ReadWindowProcessId(Window, ProcessId);
      if (ProcessId <> 0) and IsInstalledRhiProcess(ProcessId) then
      begin
        Result := Window;
        Exit;
      end;
    end;
    Window := FindNextTopLevelWindow(0, Window, 0, 0);
  end;
end;

procedure BeginForegroundHandoff;
begin
  ForegroundProgress := CreateOutputProgressPage('Starting RHI', 'Waiting for the application window...');
  ForegroundProgress.SetText('Starting RHI (including Admin Mode, if enabled)...', '');
  ForegroundProgress.Show;
end;

procedure CompleteForegroundHandoff;
var
  Window: HWND;
  ProcessId, CurrentProcessId: DWORD;
  Message: UINT;
  Attempt: Integer;
begin
  Window := 0;
  ProcessId := 0;
  try
    for Attempt := 0 to 199 do
    begin
      ForegroundProgress.SetProgress(Attempt, 200);
      Window := FindReadyRhiWindow(ProcessId);
      if Window <> 0 then Break;
      Sleep(50);
    end;
  finally
    ForegroundProgress.Hide;
  end;

  if Window = 0 then
  begin
    Log('RHI foreground handoff: no ready window within 10 seconds; normal activation remains available.');
    Exit;
  end;

  CurrentProcessId := 0;
  ReadWindowProcessId(Window, CurrentProcessId);
  if (CurrentProcessId <> ProcessId) or not IsInstalledRhiProcess(ProcessId) then Exit;
  Message := RegisterForegroundMessage(ForegroundRequestMessage);
  if Message = 0 then Exit;

  if GrantForegroundPermission(ProcessId) then
    Log(Format('RHI foreground permission granted to PID %d.', [ProcessId]))
  else
    Log(Format('RHI foreground permission refused for PID %d; RHI will use taskbar attention if necessary.', [ProcessId]));

  WizardForm.Hide;
  if not PostForegroundMessage(Window, Message, 0, 0) then
    Log('RHI foreground handoff: could not post activation request.');
end;

function NeedsWindowsAppRuntime(): Boolean;
var
  KeyPath: String;
  ResultCode: Integer;
begin
  // Check registry key written by the bootstrapper installer
  KeyPath := 'SOFTWARE\Microsoft\WindowsAppRuntime\2.5';
  if RegKeyExists(HKLM, KeyPath) or RegKeyExists(HKLM64, KeyPath) then
  begin
    Result := False;
    Exit;
  end;
  // Fallback: use PowerShell to check if the MSIX package is already installed
  // (covers cases where 2.5.1 was installed via Store/MSIX rather than the bootstrapper)
  Result := True;
  if ShellExec('', 'powershell.exe',
      '-NoProfile -NonInteractive -Command "if (Get-AppxPackage -Name Microsoft.WindowsAppRuntime.2 | Where-Object { $_.Version -like ''2.5*'' }) { exit 0 } else { exit 1 }"',
      '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    if ResultCode = 0 then
      Result := False;
  end;
end;

function IsRhiRunning(): Boolean;
var
  WMI: Variant;
  Procs: Variant;
begin
  Result := False;
  try
    WMI := CreateOleObject('WbemScripting.SWbemLocator');
    WMI := WMI.ConnectServer('.', 'root\cimv2');
    Procs := WMI.ExecQuery('SELECT * FROM Win32_Process WHERE Name="RHI.exe"');
    Result := (Procs.Count > 0);
  except
  end;
end;

function InitializeSetup(): Boolean;
var
  SignalDir, SignalPath: String;
  WaitCount: Integer;
begin
  Result := True;

  if not IsRhiRunning() then Exit;

  SignalDir := ExpandConstant('{localappdata}\RHI');
  if not DirExists(SignalDir) then
    ForceDirectories(SignalDir);
  SignalPath := SignalDir + '\rhi_shutdown_requested';
  SaveStringToFile(SignalPath, 'update', False);

  WaitCount := 0;
  while (WaitCount < 20) and IsRhiRunning() do
  begin
    Sleep(500);
    WaitCount := WaitCount + 1;
  end;

  DeleteFile(SignalPath);
end;
